// items
const menu = [
    {
        id: 1,
        title: "yogurt with cereals and berries",
        category: "breakfast",
        price: 8.99,
        img: "/images/breakfast-yogurt.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec urna nec mauris vehicula egestas. Orci varius natoque penatibus et.`,
    },
    {
        id: 2,
        title: "meat with roasted vegetables and salad",
        category: "lunch",
        price: 25.99,
        img: "/images/lunch_meat.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec urna nec mauris vehicula egestas. Orci varius natoque penatibus et.`,
    },
    {
        id: 3,
        title: "raspberry milkshake",
        category: "shakes",
        price: 10.99,
        img: "/images/shake_berries.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec urna nec mauris vehicula egestas. Orci varius natoque penatibus et.`,
    },
    {
        id: 4,
        title: "waffles with berries and ice cream",
        category: "breakfast",
        price: 6.99,
        img: "/images/breakfast_waffles.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec urna nec mauris vehicula egestas. Orci varius natoque penatibus et.`,
    },
    {
        id: 5,
        title: "ham sandwich and lettuce",
        category: "lunch",
        price: 15.99,
        img: "/images/lunch_sandwich.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec urna nec mauris vehicula egestas. Orci varius natoque penatibus et.`,
    },
    {
        id: 6,
        title: "coffee milkshake",
        category: "shakes",
        price: 12.99,
        img: "/images/shake_coffee.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec urna nec mauris vehicula egestas. Orci varius natoque penatibus et.`,
    },
    {
        id: 7,
        title: "eggs, vegetables and toasted bread",
        category: "breakfast",
        price: 10.99,
        img: "/images/breakfast_eggs.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec urna nec mauris vehicula egestas. Orci varius natoque penatibus et.`,
    },
    {
        id: 8,
        title: "fondant, ice cream and caramel",
        category: "lunch",
        price: 30.99,
        img: "/images/lunch_dessert.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec urna nec mauris vehicula egestas. Orci varius natoque penatibus et.`,
    },
    {
        id: 9,
        title: "chocolate milkshake",
        category: "shakes",
        price: 15.99,
        img: "/images/shake_chocolate.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec urna nec mauris vehicula egestas. Orci varius natoque penatibus et.`,
    },
];
